// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect } from "react";
import { useGLTF, useAnimations, useVideoTexture } from "@react-three/drei";
import gsap from "gsap";
import { useGSAP } from "@gsap/react";
import * as THREE from "three";

const MyRoom = ({ texture, ...rest }: { texture?: string }) => {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "/models/isometric_room_fin.glb",
    true
  );
  const { actions } = useAnimations(animations, group);
  console.log(actions);
  const txt = useVideoTexture(
    texture ? texture : "/textures/project/project1.mp4"
  );

  useEffect(() => {
    if (txt) {
      txt.flipY = false;
    }
  }, [txt]);

  // call animation and add delay
  useEffect(() => {
    const action = actions["Cylinder.006_0Action.004"];
    if (!action) return;

    action.setLoop(THREE.LoopOnce, 1); // play only once

    const playWithDelay = () => {
      action.reset().fadeIn(0.5).play();
      const duration = action.getClip().duration;

      setTimeout(() => {
        playWithDelay(); // replay after animation ends + 3s
      }, (duration + 3) * 1000);
    };

    playWithDelay();
  }, [actions]);

  useGSAP(() => {
    if (group.current) {
      gsap.from(group.current.rotation, {
        y: Math.PI / 2,
        duration: 1,
        ease: "power3.out",
      });
      group.current.traverse((child) => {
        if (child.isMesh) {
          child.castShadow = true;
          child.receiveShadow = true;
        }
      });
    }
  }, [txt]);

  return (
    <group ref={group} {...rest} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Root">
            <group
              name="AnimatedCup"
              position={[0.011, 0.392, 0.532]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                name="Cup"
                castShadow
                receiveShadow
                geometry={nodes.Cup.geometry}
                material={materials["material_8.002"]}
                position={[0, 0.063, 0]}
                rotation={[-1.564, 0.005, 0.643]}
                scale={[0.063, 0.055, 0.085]}
              />
              <mesh
                name="Steam"
                castShadow
                receiveShadow
                geometry={nodes.Steam.geometry}
                material={nodes.Steam.material}
                position={[0.001, 0.075, -0.001]}
                rotation={[0, 0, -Math.PI]}
                scale={[0.022, 0.001, 0.021]}
              />
              <group
                name="SteamWind"
                position={[0.005, 0.139, 0.022]}
                rotation={[-1.564, -0.004, -0.553]}
                scale={[0.824, 0.531, 1.034]}
              />
            </group>
            <group
              name="Cube011"
              position={[0.006, 0, 0]}
              rotation={[0, 0, -Math.PI]}
            >
              <mesh
                name="Cube_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube_0.geometry}
                material={materials["WALLS.005"]}
              />
              <mesh
                name="Cube_1"
                castShadow
                receiveShadow
                geometry={nodes.Cube_1.geometry}
                material={materials["FLOOR.005"]}
              />
              <mesh
                name="Cube_2"
                castShadow
                receiveShadow
                geometry={nodes.Cube_2.geometry}
                material={materials["material_21.005"]}
              />
            </group>
            <group
              name="Cube012"
              position={[-0.35, 0.272, 0.53]}
              rotation={[0, 0, -Math.PI]}
              scale={[0.432, 0.276, 0.033]}
            >
              <mesh
                name="Cube001_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube001_0.geometry}
                material={materials["material.005"]}
              />
            </group>
            <group
              name="Cube013"
              position={[0.894, -0.238, 0.219]}
              scale={[0.041, 0.048, 0.213]}
            >
              <mesh
                name="Cube005_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube005_0.geometry}
                material={materials["material.005"]}
              />
            </group>
            <group
              name="Cube014"
              position={[0.015, -0.591, 0.513]}
              rotation={[0.082, -0.067, 1.614]}
              scale={[0.872, 1.167, 0.492]}
            >
              <mesh
                name="Cube007_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube007_0.geometry}
                material={materials["shelves.010"]}
              />
            </group>
            <group
              name="Cube015"
              position={[0.015, -0.591, 0.238]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[0.363, 0.887, 0.099]}
            >
              <mesh
                name="Cube003_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube003_0.geometry}
                material={materials["material.005"]}
              />
            </group>
            <group
              name="Cube016"
              position={[0.015, -0.591, 0.286]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[0.352, 0.861, 0.096]}
            >
              <mesh
                name="Cube004_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube004_0.geometry}
                material={materials["Root.005"]}
              />
            </group>
            <group
              name="Cube017"
              position={[-0.863, -0.591, 0.29]}
              scale={[0.041, 0.048, 0.24]}
            >
              <mesh
                name="Cube006_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube006_0.geometry}
                material={materials["material.005"]}
              />
            </group>
            <group
              name="Cube018"
              position={[-0.85, -0.591, 0.462]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[0.363, 0.887, 0.032]}
            >
              <mesh
                name="Cube009_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube009_0.geometry}
                material={materials["material.005"]}
              />
            </group>
            <group
              name="Cube019"
              position={[-1.095, 0, 0.609]}
              scale={[0.14, 0.712, 0.027]}
            >
              <mesh
                name="Cube010_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube010_0.geometry}
                material={materials["white.005"]}
              />
            </group>
            <group
              name="Cube020"
              position={[-0.488, 0, 0.05]}
              rotation={[0, 0, -Math.PI]}
              scale={[0.556, 1.089, 0.999]}
            >
              <mesh
                name="Cube011_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube011_0.geometry}
                material={materials["white.005"]}
              />
            </group>
            <group
              name="Cube021"
              position={[-1.084, 0.006, 1.155]}
              scale={[-0.056, -0.038, -0.55]}
            >
              <mesh
                name="Cube008_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube008_0.geometry}
                material={materials["white.005"]}
              />
            </group>
            <group
              name="Cube022"
              position={[-0.62, -0.563, 0.394]}
              rotation={[-0.122, -0.032, -0.131]}
              scale={[0.207, 0.302, 0.068]}
            >
              <mesh
                name="Cube012_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube012_0.geometry}
                material={materials["poduha.005"]}
              />
            </group>
            <group
              name="Cube023"
              position={[0.246, -0.403, 1.37]}
              rotation={[-1.218, 0.361, -0.994]}
              scale={[0.942, 0.79, 0.573]}
            >
              <mesh
                name="Cube023_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube023_0.geometry}
                material={materials["Material.017"]}
              />
            </group>
            <group
              name="Cube024"
              position={[-0.216, 0.903, 1.539]}
              scale={[0.273, 0.077, 0.009]}
            >
              <mesh
                name="Cube019_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube019_0.geometry}
                material={materials["shelves.011"]}
              />
            </group>
            <group
              name="Cube025"
              position={[-0.215, 0.824, 1.266]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.273, 0.283, 0.009]}
            >
              <mesh
                name="Cube020_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube020_0.geometry}
                material={materials["shelves.011"]}
              />
            </group>
            <group
              name="Cube026"
              position={[-0.478, 0.903, 1.539]}
              scale={[0.273, 0.088, 0.009]}
            >
              <mesh
                name="Cube013_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube013_0.geometry}
                material={materials["shelves.011"]}
              />
            </group>
            <group
              name="Cube027"
              position={[0.45, 0.824, 1.266]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.273, 0.283, 0.009]}
            >
              <mesh
                name="Cube018_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube018_0.geometry}
                material={materials["shelves.011"]}
              />
            </group>
            <group
              name="Cube028"
              position={[0.45, 0.903, 1.539]}
              scale={[0.273, 0.077, 0.009]}
            >
              <mesh
                name="Cube017_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube017_0.geometry}
                material={materials["shelves.011"]}
              />
            </group>
            <group
              name="Cube029"
              position={[0.177, 0.903, 1.539]}
              scale={[0.273, 0.088, 0.009]}
            >
              <mesh
                name="Cube014_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube014_0.geometry}
                material={materials["shelves.011"]}
              />
            </group>
            <group
              name="Cube030"
              position={[-0.35, 0.637, 0.26]}
              rotation={[0, 0, 0.404]}
              scale={[0.158, 0.158, 0.025]}
            >
              <mesh
                name="Cube015_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube015_0.geometry}
                material={materials["lamp_wood.005"]}
              />
              <mesh
                name="Cube015_1"
                castShadow
                receiveShadow
                geometry={nodes.Cube015_1.geometry}
                material={materials["poduha.005"]}
              />
            </group>
            <group
              name="Cube031"
              position={[-0.978, 0.273, 0.296]}
              scale={[-0.012, -0.558, -0.2]}
            >
              <mesh
                name="Cube016_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube016_0.geometry}
                material={materials["tubes.005"]}
              />
            </group>
            <group
              name="Cube032"
              position={[0.639, 0.713, 0.218]}
              scale={[-0.26, -0.21, -0.15]}
            >
              <mesh
                name="Cube021_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube021_0.geometry}
                material={materials["shade.015"]}
              />
              <mesh
                name="Cube021_1"
                castShadow
                receiveShadow
                geometry={nodes.Cube021_1.geometry}
                material={materials["material.005"]}
              />
            </group>
            <group
              name="Cube033"
              position={[0.155, 0.875, 1.588]}
              scale={[-0.329, -0.21, -0.006]}
            >
              <mesh
                name="Cube022_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube022_0.geometry}
                material={materials["material.005"]}
              />
            </group>
            <group
              name="Cube034"
              position={[0.869, -0.705, 0.064]}
              rotation={[0, 0, -0.306]}
              scale={[0.066, 0.141, 0.058]}
            >
              <mesh
                name="Cube024_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube024_0.geometry}
                material={materials["Material.017"]}
              />
            </group>
            <group
              name="Cube035"
              position={[0.837, -0.418, 0.066]}
              rotation={[0, 0, 1.164]}
              scale={[0.066, 0.141, 0.058]}
            >
              <mesh
                name="Cube025_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube025_0.geometry}
                material={materials["lamp_wood.005"]}
              />
            </group>
            <group
              name="Cube036"
              position={[-0.467, 0.13, 0.635]}
              rotation={[1.571, 1.352, 0]}
              scale={[0.048, 0.102, 0.042]}
            >
              <mesh
                name="Cube026_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube026_0.geometry}
                material={materials["Material.017"]}
              />
              <mesh
                name="Cube026_1"
                castShadow
                receiveShadow
                geometry={nodes.Cube026_1.geometry}
                material={materials["lamp_wood.005"]}
              />
            </group>
            <group
              name="Cube037"
              position={[0.029, 0.059, 0.636]}
              rotation={[-1.571, 1.227, 3.142]}
              scale={[0.048, 0.102, 0.042]}
            >
              <mesh
                name="Cube027_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube027_0.geometry}
                material={materials["Material.017"]}
              />
              <mesh
                name="Cube027_1"
                castShadow
                receiveShadow
                geometry={nodes.Cube027_1.geometry}
                material={materials["lamp_wood.005"]}
              />
            </group>
            <group
              name="Cube038"
              position={[-0.319, 0.08, 0.564]}
              rotation={[Math.PI, 0, -1.913]}
              scale={[0.035, 0.074, 0.03]}
            >
              <mesh
                name="Cube028_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube028_0.geometry}
                material={materials["Material.017"]}
              />
            </group>
            <group
              name="Cube039"
              position={[0.987, 0.796, 0.068]}
              rotation={[0, 0, 0.064]}
              scale={[0.066, 0.141, 0.058]}
            />
            <group
              name="Cube040"
              position={[-0.57, 0.871, 1.612]}
              rotation={[0, 0, 1.614]}
              scale={[0.066, 0.129, 0.058]}
            >
              <mesh
                name="Cube030_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube030_0.geometry}
                material={materials["FLOOR.005"]}
              />
            </group>
            <group
              name="Cube041"
              position={[-0.57, 0.871, 1.733]}
              rotation={[0, 0, 2.069]}
              scale={[0.048, 0.07, 0.06]}
            >
              <mesh
                name="Cube031_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube031_0.geometry}
                material={materials["table.005"]}
              />
            </group>
            <group
              name="Cube042"
              position={[-0.365, 0.871, 1.349]}
              rotation={[0, 0, 1.073]}
              scale={[0.061, 0.089, 0.07]}
            >
              <mesh
                name="Cube032_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube032_0.geometry}
                material={materials["white.005"]}
              />
            </group>
            <group
              name="Cube043"
              position={[0.056, 0.908, 1.118]}
              rotation={[0, 0, 0.529]}
              scale={[0.037, 0.054, 0.114]}
            >
              <mesh
                name="Cube033_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube033_0.geometry}
                material={materials["tubes.005"]}
              />
            </group>
            <group
              name="Cube044"
              position={[0.374, 0.903, 1.03]}
              scale={[-0.238, -0.152, -0.004]}
            >
              <mesh
                name="Cube034_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube034_0.geometry}
                material={materials["lamp_wood.005"]}
              />
            </group>
            <group
              name="Cube045"
              position={[-0.97, 0.866, 1.423]}
              scale={[0.011, 0.086, 0.125]}
            >
              <mesh
                name="Cube035_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube035_0.geometry}
                material={materials["lamp_wood.005"]}
              />
              <mesh
                name="Cube035_1"
                castShadow
                receiveShadow
                geometry={nodes.Cube035_1.geometry}
                material={materials["white.005"]}
              />
            </group>
            <group
              name="Cube046"
              position={[-0.97, 0.866, 1.068]}
              scale={[0.011, 0.086, 0.125]}
            >
              <mesh
                name="Cube036_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube036_0.geometry}
                material={materials["cornice.005"]}
              />
              <mesh
                name="Cube036_1"
                castShadow
                receiveShadow
                geometry={nodes.Cube036_1.geometry}
                material={materials["WEED.005"]}
              />
            </group>
            <group
              name="Cube047"
              position={[1.006, 0.986, 1.178]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={[0.013, 0.399, 0.407]}
            >
              <mesh
                name="Cube037_0"
                castShadow
                receiveShadow
                geometry={nodes.Cube037_0.geometry}
                material={materials["table.005"]}
              />
              <mesh
                name="Cube037_1"
                castShadow
                receiveShadow
                geometry={nodes.Cube037_1.geometry}
                material={materials["lamp.012"]}
              />
            </group>
            <group
              name="Cylinder003"
              position={[-0.69, 0.185, 0.84]}
              rotation={[0, 0, 0.366]}
              scale={[0.37, 0.37, 0.166]}
            />
            <group
              name="Cylinder037"
              position={[0.894, -0.238, 0.521]}
              scale={[0.073, 0.073, 0.009]}
            >
              <mesh
                name="Cylinder007_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder007_0.geometry}
                material={materials["material.005"]}
              />
            </group>
            <group
              name="Cylinder038"
              position={[-0.866, -0.238, 0.585]}
              scale={[0.073, 0.073, 0.009]}
            >
              <mesh
                name="Cylinder008_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder008_0.geometry}
                material={materials["material.005"]}
              />
            </group>
            <group
              name="Cylinder039"
              position={[0.89, -0.808, 0.383]}
              rotation={[Math.PI, 0, -Math.PI / 2]}
              scale={[0.03, 0.03, 0.05]}
            >
              <mesh
                name="Cylinder015_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder015_0.geometry}
                material={materials["cornice.005"]}
              />
            </group>
            <group
              name="Cylinder041"
              position={[-0.69, 0.185, 0.598]}
              rotation={[0, 0, 0.366]}
              scale={[0.305, 0.305, 0.102]}
            >
              <mesh
                name="Cylinder001_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder001_0.geometry}
                material={materials["lamp_wood.005"]}
              />
            </group>
            <group
              name="Cylinder042"
              position={[-0.69, 0.185, 0.817]}
              rotation={[0, 0, 0.366]}
              scale={[0.227, 0.227, 0.102]}
            >
              <mesh
                name="Cylinder002_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder002_0.geometry}
                material={materials["lamp_light.005"]}
              />
            </group>
            <group
              name="Cylinder043"
              position={[-0.69, 0.185, 0.84]}
              rotation={[0, 0, 0.366]}
              scale={[0.367, 0.367, 0.165]}
            >
              <mesh
                name="Cylinder003_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder003_0.geometry}
                material={materials["lamp_wood.005"]}
              />
            </group>
            <group
              name="Cylinder044"
              position={[-0.947, -0.885, 1.883]}
              rotation={[Math.PI / 2, Math.PI / 2, 0]}
              scale={0.05}
            >
              <mesh
                name="Cylinder014_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder014_0.geometry}
                material={materials["cornice.005"]}
              />
            </group>
            <group
              name="Cylinder045"
              position={[-0.871, -0.001, 1.884]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.072, 0.072, 0.859]}
            >
              <mesh
                name="Cylinder004_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder004_0.geometry}
                material={materials["material.005"]}
              />
            </group>
            <group
              name="Cylinder046"
              position={[-0.912, -0.001, 1.851]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.017, 0.017, 0.901]}
            >
              <mesh
                name="Cylinder005_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder005_0.geometry}
                material={materials["cornice.005"]}
              />
            </group>
            <group
              name="Cylinder047"
              position={[-0.932, -0.551, 1.865]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.072, 0.076, 0.353]}
            >
              <mesh
                name="Cylinder006_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder006_0.geometry}
                material={materials["shade.016"]}
                morphTargetDictionary={
                  nodes.Cylinder006_0.morphTargetDictionary
                }
                morphTargetInfluences={
                  nodes.Cylinder006_0.morphTargetInfluences
                }
                position={[0.307, 0, -0.071]}
              />
            </group>
            <group
              name="Cylinder048"
              position={[-0.958, 0.73, 0.985]}
              scale={[0.053, 0.053, 1.073]}
            >
              <mesh
                name="Cylinder010_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder010_0.geometry}
                material={materials["tubes.005"]}
              />
            </group>
            <group
              name="Cylinder049"
              position={[-0.871, 0.125, 1.875]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.087, 0.087, 0.972]}
            >
              <mesh
                name="Cylinder011_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder011_0.geometry}
                material={materials["cornice.005"]}
              />
            </group>
            <group
              name="Cylinder050"
              position={[-0.871, 0.7, 1.875]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.087, 0.087, 0.972]}
            >
              <mesh
                name="Cylinder012_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder012_0.geometry}
                material={materials["cornice.005"]}
              />
            </group>
            <group
              name="Cylinder051"
              position={[-0.958, -0.857, 0.985]}
              scale={[0.053, 0.053, 1.073]}
            >
              <mesh
                name="Cylinder013_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder013_0.geometry}
                material={materials["tubes.005"]}
              />
            </group>
            <group
              name="Cylinder052"
              position={[-0.865, -0.808, 0.423]}
              rotation={[Math.PI, 0, -Math.PI / 2]}
              scale={[0.03, 0.03, 0.088]}
            >
              <mesh
                name="Cylinder016_0"
                castShadow
                receiveShadow
                geometry={nodes.Cylinder016_0.geometry}
                material={materials["cornice.005"]}
              />
            </group>
            <mesh
              name="Cylinder_0002"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_0002.geometry}
              material={materials["lamp.020"]}
              position={[-0.69, 0.185, 0.84]}
              rotation={[0, 0, 0.366]}
              scale={[0.37, 0.37, 0.166]}
            />
            <group
              name="Laptop"
              position={[-0.306, 0.303, 0.532]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <group
                name="Plane039"
                position={[-0.156, -0.004, -0.067]}
                rotation={[0.036, 1.481, -0.061]}
                scale={[0.809, 0.679, 0.699]}
              >
                <mesh
                  name="Plane005"
                  castShadow
                  receiveShadow
                  geometry={nodes.Plane005.geometry}
                  material={materials["Material.019"]}
                />
                <mesh
                  name="Plane005_1"
                  castShadow
                  receiveShadow
                  geometry={nodes.Plane005_1.geometry}
                  material={materials["Material.020"]}
                />
              </group>
            </group>
            <group
              name="Plane018"
              position={[0.286, -0.468, 0.255]}
              rotation={[1.204, 0.463, 0.05]}
              scale={[0.585, 0.608, 0.602]}
            >
              <mesh
                name="Plane007_0"
                castShadow
                receiveShadow
                geometry={nodes.Plane007_0.geometry}
                material={materials["shade.017"]}
              />
            </group>
            <group
              name="Plane019"
              position={[0.538, 0.67, 0.611]}
              rotation={[0.102, 0.135, -0.433]}
              scale={0.221}
            >
              <mesh
                name="Plane002_0"
                castShadow
                receiveShadow
                geometry={nodes.Plane002_0.geometry}
                material={materials["poduha.005"]}
              />
            </group>
            <group
              name="Plane022"
              position={[-0.256, 0.331, 0.534]}
              rotation={[0, 0, -0.096]}
              scale={[0.132, 0.094, 0.132]}
            />
            <group
              name="Plane032"
              position={[-0.266, 0.226, 0.637]}
              rotation={[1.826, -0.093, 0.024]}
              scale={[0.132, 0.094, 0.132]}
            />
            <group
              name="Plane033"
              position={[0.118, 0.912, 1.771]}
              rotation={[1.141, 0.439, 1.843]}
              scale={[0.078, 0.028, 0.013]}
            >
              <mesh
                name="Plane003_0"
                castShadow
                receiveShadow
                geometry={nodes.Plane003_0.geometry}
                material={materials["WEED.005"]}
              />
            </group>
            <group
              name="Plane034"
              position={[0.191, 0.91, 1.739]}
              rotation={[1.145, 0.416, 1.832]}
              scale={[0.057, 0.021, 0.01]}
            >
              <mesh
                name="Plane004_0"
                castShadow
                receiveShadow
                geometry={nodes.Plane004_0.geometry}
                material={materials["WEED.005"]}
              />
            </group>
            <group
              name="Plane035"
              position={[0.082, 0.852, 1.771]}
              rotation={[0.196, 1.176, 3.01]}
              scale={[0.057, 0.021, 0.01]}
            >
              <mesh
                name="Plane005_0"
                castShadow
                receiveShadow
                geometry={nodes.Plane005_0.geometry}
                material={materials["WEED.005"]}
              />
            </group>
            <group
              name="Plane036"
              position={[0.147, 0.828, 1.722]}
              rotation={[-1.164, -0.305, -1.362]}
              scale={[0.057, 0.021, 0.01]}
            >
              <mesh
                name="Plane006_0"
                castShadow
                receiveShadow
                geometry={nodes.Plane006_0.geometry}
                material={materials["WEED.005"]}
              />
            </group>
            <group
              name="Plane037"
              position={[-0.498, 0.309, 0.533]}
              rotation={[0, 0, 0.377]}
              scale={[0.067, 0.055, 0.055]}
            >
              <mesh
                name="Plane008_0"
                castShadow
                receiveShadow
                geometry={nodes.Plane008_0.geometry}
                material={materials["FLOOR.005"]}
              />
            </group>
            <group
              name="Plane038"
              position={[0.033, 0.352, 0.077]}
              rotation={[1.826, -0.093, 0.024]}
              scale={[0.068, 0.048, 0.068]}
            />
            <group name="Point001" position={[-0.693, 0.187, 0.888]}>
              <group name="Point002" />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/models/isometric_room_fin.glb", true);

export default MyRoom;
